Httpx mocking
DurgNomis-drol/mytoyota pull request #298
Opened 2024-01-13 18:10 UTC by GitOldGrumpy

This adds a series of tests using httpx_mock and static data files. The work to add the tests has identified two issues:
- During authentication the response from sending the username was not checked correctly. It will actually tell you if the username is invalid.
- For some reason we were always requested the trips for the current day when requesting the static data. I'm not sure why.

I could break these two issues out into multiple pull requests but for the minute they are contained in this pull request.

The merge looks large but this is to do with all the new static JSON files.

2024-01-13 18:38 UTC, GitOldGrumpy commented
@CM000n I cant add the required package(pytest-httpx) to poetry as it requires python >=3.9 according to poetry. I know it works fine on `Python 3.8.18 (default, Aug 25 2023, 13:20:30)` as that is my development environment. Is there a way around this?

2024-01-13 19:47 UTC, CM000n commented
> @CM000n I cant add the required package(pytest-httpx) to poetry as it requires python >=3.9 according to poetry. I know it works fine on `Python 3.8.18 (default, Aug 25 2023, 13:20:30)` as that is my development environment. Is there a way around this?

Unfortunately not. If these are the minimum requirements specified for `pytest-httpx`, there is no sensible way around this.
Of course, we could also drop support for Python 3.8. But this is a fundamental decision that should also be approved by @DurgNomis-drol.

2024-01-14 12:50 UTC, DurgNomis-drol commented
Please divide you PR into smaller ones, it makes it a lot easier, and faster to approve them ❤️

2024-01-14 12:51 UTC, DurgNomis-drol commented
@CM000n I believe @joro75 is depended on 3.8

2024-01-14 14:40 UTC, GitOldGrumpy commented
If you look at the code changes they are fairly small, the reason that the pull request is so large is because of the JSON files that provide the data for the tests.

2024-01-14 15:26 UTC, DurgNomis-drol commented
@GitOldGrumpy  Personally I would prefer if we could remove support for .8 and .9, but @joro75 is supporting it. So I think to be fair, he should be involved in the decision

2024-01-14 17:01 UTC, CM000n commented
So let's hope for a prompt response from @joro75. But I would also prefer to completely discontinue support for 3.8 rather than simply disconnect the tests for it.

2024-01-16 08:08 UTC, CM000n commented
Oh dear, it looks like Domoticz, for which @joro75 maintains the Toyota plugin, is not exactly up to date as far as the python versions are concerned: https://www.domoticz.com/wiki/Using_Python_plugins#Required:_install_Python 🙄 
So we will probably have to maintain support for python 3.9 for the time being @DurgNomis-drol.

2024-01-16 21:10 UTC, CM000n requested changes

2024-01-16 21:10 UTC, CM000n commented on pyproject.toml
> +pytest-httpx = "^0.28.0"
This should go under dev-dependencies 😉

2024-01-16 21:14 UTC, GitOldGrumpy commented on pyproject.toml
> +pytest-httpx = "^0.28.0"
poetry & toml is all new to me!

2024-01-16 21:16 UTC, CM000n commented on pyproject.toml
> +pytest-httpx = "^0.28.0"
No criticism, just a hint 😊

2024-01-16 22:53 UTC, GitOldGrumpy commented on tests/test_mocks.py
Re-ordered.

2024-01-16 23:16 UTC, GitOldGrumpy commented on tests/test_mocks.py
> +def build_routes(httpx_mock, filenames: List[str]) -> None:  # noqa: D103
If you could give me some pointers on this one? I worked out how to turn remove_cache into a fixture maybe incorrectly, so you might want to check that. I cant seem to apply this to the convert this to a fixture. I need access to httpx_mock which is provided by another fixture.

2024-01-16 23:32 UTC, GitOldGrumpy commented on tests/test_mocks.py
> +    with open("./data/mocks/cached_token.json") as f:  # noqa: ASYNC101. I dont see this as a problem in test code
Done.

2024-01-17 00:03 UTC, GitOldGrumpy commented
@CM000n you might want to double check my attempts to eradicate 3.8 from building. I was also not sure if we need to update the poetry file so that `python-versions ` on the `[[package]]` are now also 3.9?

2024-01-17 07:34 UTC, CM000n requested changes

2024-01-17 07:34 UTC, CM000n commented on mytoyota/controller.py
> +                #                print(f"{format_httpx_response_json(resp)},", flush=True)
This commented out print statement should be removed before the merge.

2024-01-17 07:34 UTC, CM000n commented on mytoyota/controller.py
> +            #            print(f"{format_httpx_response_json(resp)},", flush=True)
This commented out print statement should be removed before the merge.

2024-01-17 07:34 UTC, CM000n commented on mytoyota/controller.py
> +            #            print(f"{format_httpx_response_json(resp)},", flush=True)
This commented out print statement should be removed before the merge.

2024-01-17 07:34 UTC, CM000n commented on mytoyota/controller.py
> +            #            print(f"{format_httpx_response_json(resp)},", flush=True)
This commented out print statement should be removed before the merge.

2024-01-17 07:34 UTC, CM000n commented on mytoyota/controller.py
> +            #            print(f"{format_httpx_response_json(response)},", flush=True)
This commented out print statement should be removed before the merge.

2024-01-17 07:34 UTC, CM000n commented on tests/integration_tests/conftest.py
> +    return f"{Path(request.module.__file__).parent}/data"
You don't need an f-string here:
`str(Path(request.module.__file__).parent / "data")`

2024-01-17 07:34 UTC, CM000n commented on tests/unit_tests/conftest.py
> +    return f"{Path(request.module.__file__).parent}/data"
You don't need an f-string here:
`str(Path(request.module.__file__).parent / "data")`

2024-01-17 07:34 UTC, CM000n commented on tests/unit_tests/conftest.py
> +@pytest.fixture
I think the scope for this ficture can be at least `module`, right?

2024-01-17 07:34 UTC, CM000n commented on tests/integration_tests/conftest.py
> +@pytest.fixture
I think the scope for this ficture can be at least `module`, right?

2024-01-17 07:36 UTC, CM000n commented
> @CM000n you might want to double check my attempts to eradicate 3.8 from building. I was also not sure if we need to update the poetry file so that `python-versions ` on the `[[package]]` are now also 3.9?

Looks good to me so far 😊  You should only also remove the entry for Python 3.8 in the `classifiers` in the `pyproject.toml` file

2024-01-24 09:00 UTC, CM000n commented
Mhmm, doesn't look like @joro75 is particularly active. I actually don't want to wait too long as these changes are very beneficial in terms of test coverage.

What do you think @DurgNomis-drol? Should we give ourselves a specific timeframe here for feedback from @joro75 and merge the changes otherwise?

2024-01-25 17:33 UTC, joro75 commented
Hi all,

Sorry for the delay. I have been busy, and have not been able to follow all the recent changes.

Dropping Python 3.8 is OK for me. I also plan to update Domoticz-Toyota-Plugin to Python 3.9 soon, also updating it to the latest mytoyota. 
It is correct that the original Domoticz documentation regarding python is old. Using Python >= 3.9 in combination with Python is possible, as I recently updated my own installation to Python 3.9.

Just drop Python 3.8, and continue with the merge!

2024-01-25 18:29 UTC, CM000n commented
Thanks for you response @joro75 😊

2024-01-25 20:03 UTC, CM000n approved these changes

2024-01-26 07:16 UTC, merged